// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DonFlorito.Models
{
    public partial class EstadoReserva
    {
        public EstadoReserva()
        {
            Reserva = new HashSet<Reserva>();
        }

        public long Id { get; set; }
        public string Nombre { get; set; }

        public virtual ICollection<Reserva> Reserva { get; set; }
    }
}