// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DonFlorito.Models
{
    public partial class OrdenCompra
    {
        public OrdenCompra()
        {
            Voucher = new HashSet<Voucher>();
        }

        public long Id { get; set; }
        public string Token { get; set; }
        public string Url { get; set; }
        public DateTime Fecha { get; set; }
        public long? IdReserva { get; set; }
        public bool IsUsed { get; set; }

        public virtual Reserva IdReservaNavigation { get; set; }
        public virtual ICollection<Voucher> Voucher { get; set; }
    }
}