// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DonFlorito.Models
{
    public partial class Persona
    {
        public Persona()
        {
            Reserva = new HashSet<Reserva>();
            Usuario = new HashSet<Usuario>();
        }

        public long Id { get; set; }
        public string Rut { get; set; }
        public string Nombre { get; set; }
        public string SegundoNombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Email { get; set; }
        public long Telefono { get; set; }
        public bool IsEnabled { get; set; }

        public virtual ICollection<Reserva> Reserva { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}