// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DonFlorito.Models
{
    public partial class PrecioServicio
    {
        public PrecioServicio()
        {
            ReservaServicio = new HashSet<ReservaServicio>();
        }

        public long Id { get; set; }
        public long IdTipoServicio { get; set; }
        public long Precio { get; set; }
        public long? Minutos { get; set; }
        public bool IsEnabled { get; set; }

        public virtual TipoServicio IdTipoServicioNavigation { get; set; }
        public virtual ICollection<ReservaServicio> ReservaServicio { get; set; }
    }
}