// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DonFlorito.Models
{
    public partial class ReservasEspeciales
    {
        public long Id { get; set; }
        public long? IdServicio { get; set; }
        public long? IdTipoServicio { get; set; }
        public DateTime FechaComienzo { get; set; }
        public DateTime FechaTermino { get; set; }
        public bool IsCanchas { get; set; }
        public bool IsCamping { get; set; }
        public bool IsEnabled { get; set; }

        public virtual Servicio IdServicioNavigation { get; set; }
        public virtual TipoServicio IdTipoServicioNavigation { get; set; }
    }
}