// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DonFlorito.Models
{
    public partial class ReservaServicio
    {
        public long Id { get; set; }
        public long IdReserva { get; set; }
        public long IdServicio { get; set; }
        public long IdPrecioServicio { get; set; }
        public long Cantidad { get; set; }
        public DateTime? HoraComienzo { get; set; }

        public virtual PrecioServicio IdPrecioServicioNavigation { get; set; }
        public virtual Reserva IdReservaNavigation { get; set; }
        public virtual Servicio IdServicioNavigation { get; set; }
    }
}