// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DonFlorito.Models
{
    public partial class Voucher
    {
        public long Id { get; set; }
        public string Vci { get; set; }
        public long? Amount { get; set; }
        public string Status { get; set; }
        public string BuyOrder { get; set; }
        public string SessionId { get; set; }
        public string CardNumber { get; set; }
        public string AccountingDate { get; set; }
        public string TransactionDate { get; set; }
        public string AuthorizationCode { get; set; }
        public string PaymentTypeCode { get; set; }
        public long? ResponseCode { get; set; }
        public long? InstallmentsAmount { get; set; }
        public long? InstallmentsNumber { get; set; }
        public long? Balance { get; set; }
        public long IdOrdenCompra { get; set; }
        public DateTime Fecha { get; set; }

        public virtual OrdenCompra IdOrdenCompraNavigation { get; set; }
    }
}